// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfqsbjqvdpolldydvpbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmcXNianF2ZHBvbGxkeWR2cGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTMzMDgsImV4cCI6MjA3MTc2OTMwOH0.fJakwgWWX5jsrWgrG5fzB60xgrV9SvxJ5uatHz2BMFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});